# Generated by Django 3.0.5 on 2020-05-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='scheduleTime',
            field=models.DateTimeField(null=True),
        ),
    ]
